"""project updated

Revision ID: d8f7a6f4cb8f
Revises: 375eaa1e6eb7
Create Date: 2026-02-28 19:02:59.740041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f7a6f4cb8f'
down_revision: Union[str, None] = '375eaa1e6eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_status')
    # ### end Alembic commands ###
